name: Deploy to Azure Function App

on:
  push:
    branches: [ "main" ]  # or your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16' 
          # or 18 if the project requires it; 
          # match the version that CIPP normally uses

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build 
        # This might differ depending on how the CIPP project is structured

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: "cipp7duey"  # Your function app name
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
